// vue2/src/components/layout/NavBar.vue
<template>
  <nav class="navbar-container">
    <router-link class="navbar-link" v-for="(link, key) in links" :key="key" :to="{ name: link.name }">
      <i class="link-icon">
        <font-awesome-icon :icon="['fas', link.icon]" />
      </i>
      <span class="link-text">{{ $t(link.name) }}</span>
    </router-link>
  </nav>
</template>

<script>
export default {
  name: 'NavBar',
  data() {
    return {
      links: [
        {
          name: 'home',
          icon: 'home'
        },
        {
          name: 'art',
          icon: 'palette'
        },
        {
          name: 'bugs',
          icon: 'bug'
        },
        {
          name: 'fishes',
          icon: 'fish'
        },
        {
          name: 'fossils',
          icon: 'bone'
        }
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
@use 'sass:math';
@import '../../assets/css/_variables.scss';

.navbar-container {
  background-color: $secondary-color;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-evenly;
  list-style: none;
  padding: 0;
  margin: 0;
  overflow: hidden;
  filter: grayscale(20%);

  @media screen and (min-width: #{$tablet-breakpoint}) {
    flex-direction: column;
    align-items: flex-start;
    justify-content: start;

    &:hover {
      .link-text {
        display: block;
      }
    }
  }
}

.navbar-link {
  display: flex;
  align-items: center;
  height: $navbar-size;
  text-decoration: none;
  color: $tertiary-color;
  filter: grayscale(20%) opacity(0.6);
  transition: $transition-speed;

  &:hover {
    filter: grayscale(0%) opacity(1);
  }

  @media screen and (min-width: #{$tablet-breakpoint}) {
    width: 100%;
  }
}

.link-icon {
  height: $navbar-size;
  width: $navbar-size;

  & > svg {
    height: math.div($navbar-size, 2);
    width: math.div($navbar-size, 2);
    margin: math.div($navbar-size, 4);
  }
}

.link-text {
  display: none;
  margin: 0 1rem;
  font-size: 1.4rem;
  font-weight: bold;
  white-space: nowrap;

  @media screen and (min-width: #{$desktop-breakpoint}) {
    display: block;
  }
}

.router-link-exact-active {
  background-color: $tertiary-color;
  color: $primary-color;
}
</style>

// src/components/layout/NavBar.svelte
<script>
  import { page } from '$app/stores';
  import { faHome, faBug, faFish, faBone } from '@fortawesome/free-solid-svg-icons';
  import Icon from 'svelte-awesome';
  import { _ } from 'svelte-i18n';

  $: isActive = (pathname) => $page.url.pathname === pathname;

  const links = [
    { name: 'home', href: '/', icon: faHome },
    { name: 'bugs', href: '/bugs', icon: faBug },
    { name: 'fishes', href: '/fishes', icon: faFish },
    { name: 'fossils', href: '/fossils', icon: faBone }
  ];
</script>

<nav
  class="group duration-1000 transition-maxw fixed bottom-0 z-10 flex flex-row md:flex-col md:max-w-[60px] md:justify-start w-screen md:hover:w-max md:hover:max-w-screen-md md:w-[60px] md:h-screen md:left-0 height-60 navbar bg-secondary justify-evenly lg:relative lg:w-max lg:max-w-screen-lg filter grayscale-20 overflow-hidden"
  data-sveltekit-preload-data
>
  {#each links as { name, href, icon }}
    <a
      class="transition-link duration-500 flex gap-3 items-center h-[60px] text-tertiary filter grayscale-20 opacity-60 hover:grayscale-0 hover:opacity-100"
      {href}
      class:active={isActive(href)}
    >
      <i class="w-[60px] h-[60px]">
        <Icon data={icon} scale="1" class="h-[30px] w-[30px] m-[15px]" />
      </i>
      <span
        class="hidden ml-2 mr-4 text-2xl font-bold whitespace-nowrap md:group-hover:block lg:block"
        >{$_(name)}</span
      >
    </a>
  {/each}
</nav>

<style lang="scss">
  .active {
    @apply text-secondary bg-tertiary;
  }
</style>
